### ISSUE TITLE
nmp run build

### ISSUE THREAD

**Issue by Richardfg** [jerosoler/newpct-total#12]
Buenas noches! vaya pintaza tiene esto!

pues me da error al intentar instalarlo, no se si es por ansias o porque fallara algo de mi maquina:

C:\Users\Fuck\Desktop\Proyect_Github>npm run build

> Proyect_Github@1.0.0 build C:\Users\Fuck\Desktop\Proyect_Github
> webpack --mode production

C:\Users\Fuck\Desktop\Proyect_Github\webpack.config.js:3
        output: {
        ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at NativeCompileCache._moduleCompile (C:\Users\Fuck\Desktop\Proyect_Github\node_modules\v8-compile-cache\v8-compile-cache.js:226:18)
    at Module._compile (C:\Users\Fuck\Desktop\Proyect_Github\node_modules\v8-compile-cache\v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (C:\Users\Fuck\Desktop\Proyect_Github\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (C:\Users\Fuck\Desktop\Proyect_Github\node_modules\webpack-cli\bin\convert-argv.js:115:13)
    at requireConfig (C:\Users\Fuck\Desktop\Proyect_Github\node_modules\webpack-cli\bin\convert-argv.js:117:6)
    at C:\Users\Fuck\Desktop\Proyect_Github\node_modules\webpack-cli\bin\convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\Fuck\Desktop\Proyect_Github\node_modules\webpack-cli\bin\convert-argv.js:122:15)
    at yargs.parse (C:\Users\Fuck\Desktop\Proyect_Github\node_modules\webpack-cli\bin\cli.js:228:39)
    at Object.parse (C:\Users\Fuck\Desktop\Proyect_Github\node_modules\yargs\yargs.js:567:18)
    at C:\Users\Fuck\Desktop\Proyect_Github\node_modules\webpack-cli\bin\cli.js:206:8
    at Object.<anonymous> (C:\Users\Fuck\Desktop\Proyect_Github\node_modules\webpack-cli\bin\cli.js:500:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Fuck\Desktop\Proyect_Github\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Proyect_Github@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Proyect_Github@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Fuck\AppData\Roaming\npm-cache\_logs\2019-03-01T00_38_04_879Z-debug.log

C:\Users\Fuck\Desktop\Proyect_Github>

**Comment by jerosoler** [comment]
Has seguido los pasos de instalación correcto?
```# Download project
git clone https://github.com/jerosoler/newpct-total.git
# Entrar al directorio
cd newpct-total
# install dependencies
npm install # Or yarn install
# Montando proyecto
npm run build
# Lanzando servidor
npm start # Or pm2 start npm --name="newpct" -- start
```
Veo que estas utilizando windows, puede ser que en windows no funcione. 
Saludos

**Comment by Richardfg** [comment]
si lo reinstale el node segui tus pasos y sigue el error

**Comment by jerosoler** [comment]
Prueba con un npm run dev a ver que pasa

**Comment by Richardfg** [comment]
C:\Users\Fuck\Desktop\Proyect_Github>npm run dev
npm ERR! missing script: dev

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Fuck\AppData\Roaming\npm-cache\_logs\2019-03-01T19_07_56_860Z-debug.log

C:\Users\Fuck\Desktop\Proyect_Github>

**Comment by jerosoler** [comment]
Parece que no has descargado bien el programa.

Igualmente no esta preparado para windows.

Si utilizas windows 10 prueba con las distribuciones de windows subsystems 

https://www.genbeta.com/linux/ya-puedes-descargar-ubuntu-18-04-lts-desde-la-microsoft-store-en-windows-10

Saludos

**Comment by jerosoler** [comment]
Hola el error que te da es de vue.

Vue packages version mismatch:

vue@2.5.13
vue-server-renderer@2.6.10

Prueba a instalar.
npm install vue@2.6.10 

Y luego has el build

**Comment by ibanana** [comment]
muchas gracias jero por comentar, e quitado todo he puesto bien el node etc, y empiezo con el npm instal y update me dan este error : 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1532 packages from 798 contributors and audited 19203 packages in 15.742s
found 43 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by ibanana** [comment]
tras acerle un audit --force obtengo esto al volver hacer npm install : 

sintapujos@sintapujos:/opt/newpct-total$ npm install
npm WARN plex-api-pinauth@0.1.0 requires a peer of plex-api@^3.2.0 but none is installed. You must install peer dependencies yourself.

audited 19203 packages in 7.639s
found 43 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by ibanana** [comment]
y tras hacer el run build obtengo esto: 

`sintapujos@sintapujos:/opt/newpct-total$ npm run build

> newpct-total@1.0.0 build /opt/newpct-total
> nuxt build && backpack build


 WARN  vendor has been deprecated due to webpack4 optimization                                                                      23:12:53

ℹ Production build                                                                                                                  23:12:54
✔ Builder initialized                                                                                                               23:12:54
✔ Nuxt files generated                                                                                                              23:12:54

 WARN  BrowserslistError: Unknown browser query android all                                                                         23:12:54


✖ Client
  Compiled with some errors in 635.51ms

◯ Server
  


Hash: 4d01e1ebb3fadeb8c5f3
Version: webpack 4.34.0
Time: 637ms
Built at: 2019-06-19 23:12:56
                  Asset       Size  Chunks  Chunk Names
10e239fd543cdf3bf5c6.js   1.45 KiB       1  runtime
34881f6a3cb0afc2d8ce.js  348 bytes       0  app
Entrypoint app = 10e239fd543cdf3bf5c6.js 34881f6a3cb0afc2d8ce.js

ERROR in ./.nuxt/client.js
Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'eslint' of undefined
    at Object.module.exports (/opt/newpct-total/node_modules/eslint-loader/index.js:148:18)
 @ multi ./.nuxt/client.js app[0]

 WARN  BrowserslistError: Unknown browser query android all (repeated 683 times)                                                    23:12:54


 FATAL  Nuxt Build Error                                                                                                            23:12:56

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:5367:13)
  at <anonymous>
  at process._tickDomainCallback (internal/process/next_tick.js:229:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt Build Error   │
   │                             │
   ╰─────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! newpct-total@1.0.0 build: `nuxt build && backpack build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the newpct-total@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sintapujos/.npm/_logs/2019-06-19T21_12_56_922Z-debug.log
`
