### ISSUE TITLE
gulp

### ISSUE THREAD

**Issue by Richardfg** [jerosoler/newpct-total#13]
Hola alguie sabe de este error al ekecutar el comando buld 

C:\Users\Fuck\Desktop\proyecto>gulp
C:\Users\Fuck\Desktop\proyecto\gulpfile.js:4
gulp.taskWrapper('styles', function (){
     ^

TypeError: gulp.taskWrapper is not a function
    at Object.<anonymous> (C:\Users\Fuck\Desktop\proyecto\gulpfile.js:4:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at execute (C:\Users\Fuck\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js:36:18)
    at Liftoff.handleArguments (C:\Users\Fuck\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\index.js:175:63)

**Comment by jerosoler** [comment]
Hola
En el proyecto no se utiliza gulp y veo que has abierto otra issue #12 
Damos por cerrado!
