### ISSUE TITLE
me sale el siguiente error al ejecutarlo

### ISSUE THREAD

**Issue by mamelito** [jerosoler/newpct-total#14]
npm start

> newpct-total@1.0.0 start /home/transmission/newpct-total
> cross-env NODE_ENV=production node build/main.js

video-stream `factory.opts`: { dir: '/home/transmission/newpct-total' }
Server listening on localhost3000
JSON Server is running

{ ReferenceError: HTMLElement is not defined
    at Module.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:36822:31)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:332:18)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at /home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:85:18
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:88:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/transmission/newpct-total/node_modules/vue-server-renderer/build.prod.js:1:77626
    at Object.<anonymous> (server-bundle.js:3819:18)
    at __webpack_require__ (server-bundle.js:27:30) statusCode: 500, name: 'ReferenceError' }
{ ReferenceError: HTMLElement is not defined
    at Module.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:36822:31)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:332:18)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at /home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:85:18
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:88:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/transmission/newpct-total/node_modules/vue-server-renderer/build.prod.js:1:77626
    at Object.<anonymous> (server-bundle.js:3819:18)
    at __webpack_require__ (server-bundle.js:27:30) statusCode: 500, name: 'ReferenceError' }
{ ReferenceError: HTMLElement is not defined
    at Module.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:36822:31)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:332:18)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at /home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:85:18
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:88:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/transmission/newpct-total/node_modules/vue-server-renderer/build.prod.js:1:77626
    at Object.<anonymous> (server-bundle.js:3819:18)
    at __webpack_require__ (server-bundle.js:27:30) statusCode: 500, name: 'ReferenceError' }
{ ReferenceError: HTMLElement is not defined
    at Module.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:36822:31)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:332:18)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at /home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:85:18
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:88:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/transmission/newpct-total/node_modules/vue-server-renderer/build.prod.js:1:77626
    at Object.<anonymous> (server-bundle.js:3819:18)
    at __webpack_require__ (server-bundle.js:27:30) statusCode: 500, name: 'ReferenceError' }
{ ReferenceError: HTMLElement is not defined
    at Module.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:36822:31)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:332:18)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at /home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:85:18
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:88:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/transmission/newpct-total/node_modules/vue-server-renderer/build.prod.js:1:77626
    at Object.<anonymous> (server-bundle.js:3819:18)
    at __webpack_require__ (server-bundle.js:27:30) statusCode: 500, name: 'ReferenceError' }
{ ReferenceError: HTMLElement is not defined
    at Module.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:36822:31)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:332:18)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at /home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:85:18
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:88:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/transmission/newpct-total/node_modules/vue-server-renderer/build.prod.js:1:77626
    at Object.<anonymous> (server-bundle.js:3819:18)
    at __webpack_require__ (server-bundle.js:27:30) statusCode: 500, name: 'ReferenceError' }
{ ReferenceError: HTMLElement is not defined
    at Module.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:36822:31)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:332:18)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at /home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:85:18
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:88:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/transmission/newpct-total/node_modules/vue-server-renderer/build.prod.js:1:77626
    at Object.<anonymous> (server-bundle.js:3819:18)
    at __webpack_require__ (server-bundle.js:27:30) statusCode: 500, name: 'ReferenceError' }
{ ReferenceError: HTMLElement is not defined
    at Module.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:36822:31)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:332:18)
    at __webpack_require__ (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:21:30)
    at /home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:85:18
    at Object.<anonymous> (/home/transmission/newpct-total/node_modules/element-ui/lib/element-ui.common.js:88:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/transmission/newpct-total/node_modules/vue-server-renderer/build.prod.js:1:77626
    at Object.<anonymous> (server-bundle.js:3819:18)
    at __webpack_require__ (server-bundle.js:27:30) statusCode: 500, name: 'ReferenceError' }

**Comment by jerosoler** [comment]
Has hecho el build primero?

Prueba con **npm update** antes de hacer todo, parece ser un error de webpack.
