### ISSUE TITLE
Problema nueva actualización (log)

### ISSUE THREAD

**Issue by Znationpx** [jerosoler/newpct-total#16]
Hola @jerosoler he intentado instalar tu nuevo update pero recibo este error 
0 info it worked if it ends with ok                                             
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]                      
2 info using npm@6.11.2                                                         
3 info using node@v8.16.0                                                       
4 verbose run-script [ 'prestart', 'start', 'poststart' ]                       
5 info lifecycle newpct-total@1.0.0~prestart: newpct-total@1.0.0                
6 info lifecycle newpct-total@1.0.0~start: newpct-total@1.0.0                   
7 verbose lifecycle newpct-total@1.0.0~start: unsafe-perm in lifecycle true     
8 verbose lifecycle newpct-total@1.0.0~start: PATH: /usr/lib/node_modules/npm/n$
9 verbose lifecycle newpct-total@1.0.0~start: CWD: /opt/newpct-total            
10 silly lifecycle newpct-total@1.0.0~start: Args: [ '-c', 'cross-env NODE_ENV=$
11 silly lifecycle newpct-total@1.0.0~start: Returned: code: 1  signal: null    
12 info lifecycle newpct-total@1.0.0~start: Failed to exec start script         
13 verbose stack Error: newpct-total@1.0.0 start: `cross-env NODE_ENV=productio$
13 verbose stack Exit status 1                                                  
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/nod$
13 verbose stack     at emitTwo (events.js:126:13)                              
13 verbose stack     at EventEmitter.emit (events.js:214:7)                     
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/nod$
13 verbose stack     at emitTwo (events.js:126:13)                              
13 verbose stack     at ChildProcess.emit (events.js:214:7)                     
13 verbose stack     at maybeClose (internal/child_process.js:915:16)           
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_pro$
14 verbose pkgid newpct-total@1.0.0                                             
15 verbose cwd /opt/newpct-total                                                
16 verbose Linux 4.15.0-58-generic                                              
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"                          
18 verbose node v8.16.0                                                         
19 verbose npm  v6.11.2                                                         
20 error code ELIFECYCLE                                                        
21 error errno 1                                                                
22 error newpct-total@1.0.0 start: `cross-env NODE_ENV=production node build/ma$
22 error Exit status 1                                                          
23 error Failed at the newpct-total@1.0.0 start script.                         
23 error This is probably not a problem with npm. There is likely additional lo$
24 verbose exit [ 1, true ]

**Comment by Znationpx** [comment]
Por aquí dejo otro error a ver si ayuda ...

k Names                                                                       pages/streaming.3d02b92b20cf88f44d3c.js    3.05 kB       3  [emitted]         pages/streaming                                                                          fonts/element-icons.2fad952.woff    6.16 kB          [emitted]                              img/logo.a04e995.png    14.3 kB          [emitted]                           img/nophoto.ffc3e23.jpg    18.4 kB          [emitted]         layouts/streaming.3624f3bc647a6835c3e0.js    3.66 kB       0  [emitted]         layouts/streaming                                                                 layouts/default.9fe63429e5e288b0ffe9.js    3.67 kB       1  [emitted]         layouts/default                                                                       pages/index.de6cd764b039dba63325.js    11.6 kB       2  [emitted]         pages/index                                                                               fonts/element-icons.6f0a763.ttf      11 kB          [emitted]               pages/login.c726e1b5a49fad60ef7d.js    2.27 kB       4  [emitted]         pages/login                                                                          pages/config.987ffe783772cc5f3cc7.js    14.1 kB       5  [emitted]         pages/config
    layouts/login.8216b59a57581d234942.js  931 bytes       6  [emitted]         layouts/login
           vendor.35e052f31056f4c98da7.js     754 kB       7  [emitted]  [big]  vendor
              app.37aa3348c580199f05c8.js     231 kB       8  [emitted]         app
         manifest.d1a777c8c7d4956a0b59.js    1.69 kB       9  [emitted]         manifest
                                 LICENSES    1.28 kB          [emitted]          + 3 hidden assets

WARNING in ./middleware/auth.js

/home/dantesin/newpct-total/middleware/auth.js
  2:3  error  Expected space or tab after '//' in comment  spaced-comment

✖ 1 problem (1 error, 0 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.

 @ ./middleware nonrecursive ^\.\/(?!-)[^.]+\.(js)$
 @ ./.nuxt/middleware.js
 @ ./.nuxt/client.js

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (300 kB).
This can impact web performance.
Assets: 
  vendor.35e052f31056f4c98da7.js (754 kB)
Hash: b7de624482c3a9b40afd
Version: webpack 3.12.0
Time: 40275ms
             Asset    Size  Chunks             Chunk Names
server-bundle.json  433 kB          [emitted]  
  nuxt:build Building done +7m
 DONE  Compiled successfully in 8587ms

**Comment by jerosoler** [comment]
Por lo que veo encuentra un error que es de eslint, pero veo que al final lo hace correctamente: 
`DONE Compiled successfully in 8587ms`
Si haces un `npm start` que te sale? 

En el archivo db.json que te sale al final?
Tendria que ser así: 
```
"urlsearch": {
    "url": "https://descargas2020.org",
    "feed": "https://descargas2020.org"
  }
```

También puedes hacer una instalación limpia y copiar el archivo db.json que es donde esta toda la configuración.

**Comment by Znationpx** [comment]
> Por lo que veo encuentra un error que es de eslint, pero veo que al final lo hace correctamente:
> `DONE Compiled successfully in 8587ms`
> Si haces un `npm start` que te sale?
> 
> En el archivo db.json que te sale al final?
> Tendria que ser así:
> 
> ```
> "urlsearch": {
>     "url": "https://descargas2020.org",
>     "feed": "https://descargas2020.org"
>   }
> ```
> 
> También puedes hacer una instalación limpia y copiar el archivo db.json que es donde esta toda la configuración.

Pues al hacer npm start me sale esto :> newpct-total@1.0.0 start /opt/newpct-total
> cross-env NODE_ENV=production node build/main.js

video-stream factory.opts: { dir: '/opt/newpct-total' }
Server listening on localhost3000
JSON Server is running

Pero al entrar por web al momento me da este error:
/opt/newpct-total/build/webpack:/server/api/newpct.js:92
      var listatorrents = body.data.torrents[0];
                                    ^
TypeError: Cannot read property 'torrents' of undefined
    at Request._callback (/opt/newpct-total/build/webpack:/server/api/newpct.js:92:37)
    at Request.self.callback (/opt/newpct-total/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/opt/newpct-total/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/opt/newpct-total/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! newpct-total@1.0.0 start: cross-env NODE_ENV=production node build/main.js
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the newpct-total@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sintapujos/.npm/_logs/2019-08-28T09_15_58_717Z-debug.log

**Comment by jerosoler** [comment]
Ese error me pasa cuando en el archivo db.json
Esta en http: y no en https.
```
"urlsearch": {
    "url": "https://descargas2020.org",
    "feed": "https://descargas2020.org"
  }
```

Puedes comprobar que este correcto?

**Comment by Znationpx** [comment]
> Ese error me pasa cuando en el archivo db.json
> Esta en http: y no en https.
> 
> ```
> "urlsearch": {
>     "url": "https://descargas2020.org",
>     "feed": "https://descargas2020.org"
>   }
> ```
> 
> Puedes comprobar que este correcto?

Al ponerlo así ya no sale error y puedo acceder estaba con mejortorrent por defecto ,lo que no aparecen las carátulas de series demás ,gracias por el gran trabajo y soporte

**Comment by jerosoler** [comment]
Perfecto! El tema de las imágenes es seguridad de cloudfare mirare de solucionarlo.

**Comment by Znationpx** [comment]
> Perfecto! El tema de las imágenes es seguridad de cloudfare mirare de solucionarlo.

Hola @jerosoler ,se lueee hacer algo ya con las imágenes que no las muestra? Gracias de antemano

**Comment by jerosoler** [comment]
Lo tengo un poco abandonado. Me parece que si cargas la pagina de descargas 2020 y después cargas la pagina de la aplicación se la salta la protección.

**Comment by Znationpx** [comment]
> Lo tengo un poco abandonado. Me parece que si cargas la pagina de descargas 2020 y después cargas la pagina de la aplicación se la salta la protección.

 Voy a probar a ver

**Comment by Znationpx** [comment]
> Lo tengo un poco abandonado. Me parece que si cargas la pagina de descargas 2020 y después cargas la pagina de la aplicación se la salta la protección.

A mi no me ha funcionado 😢

**Comment by jerosoler** [comment]
El servidor esta en la misma máquina, con la que entras? 
Podria ser por eso :S

**Comment by Znationpx** [comment]
> El servidor esta en la misma máquina, con la que entras?
> Podria ser por eso :S

No,no lo está

**Comment by bepece1** [comment]
a alguien le muestra las imágenes de las caratulas desde el móvil???
Yo he probado varios navegadores en iPhone y en ninguno se muestran....
¿se puede hacer algo o es normal que en navegadores de móvil la protección cloudfare sea más estricta?
