### ISSUE TITLE
Error al selecciona descarga

### ISSUE THREAD

**Issue by Spufy** [jerosoler/newpct-total#9]
Hola, en primer lugar te felicito por tu trabajo.
He creado un docker con transmission y he conseguido instalar newpct-total. El servidor arranca perfectamente y cuando selecciono una película para descargar me aparece el siguiente error:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v11.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle newpct-total@1.0.0~prestart: newpct-total@1.0.0
6 info lifecycle newpct-total@1.0.0~start: newpct-total@1.0.0
7 verbose lifecycle newpct-total@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle newpct-total@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/abc/newpct-total/node_modules/.bin:/usr/local/sbin:/usr/loc$
9 verbose lifecycle newpct-total@1.0.0~start: CWD: /home/abc/newpct-total
10 silly lifecycle newpct-total@1.0.0~start: Args: [ '-c', 'cross-env NODE_ENV=production node build/main.js' ]
11 silly lifecycle newpct-total@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle newpct-total@1.0.0~start: Failed to exec start script
13 verbose stack Error: newpct-total@1.0.0 start: `cross-env NODE_ENV=production node build/main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid newpct-total@1.0.0
15 verbose cwd /home/abc/newpct-total
16 verbose Linux 4.15.0-42-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v11.4.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error newpct-total@1.0.0 start: `cross-env NODE_ENV=production node build/main.js`
22 error Exit status 1
23 error Failed at the newpct-total@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Te agredecería si pudieras indicarme el posible fallo cometido.
Gracias

**Comment by jerosoler** [comment]
Hola, 
Veo que utilizar la versión de node 11.4.0

Prueba de instalar-lo así:
https://github.com/jerosoler/newpct-total/issues/8#issuecomment-440740238
Ya me dices.

Prueba también en la pagina de configuración con "descargas2020" que ahora esta funcionado. 
Supongo que tienes bien configurada las opciones de transmission y instalado el paquete transmission-remote. 

Saludos,

**Comment by Spufy** [comment]
Hola, así lo he hecho.

**Comment by jerosoler** [comment]
Hola,

Perfecto, prueba y me dices.
Para saber si tienes instalado transmission-remote
`transmission-remote -V`

Ya que parece que falla en la ejecución del processo child.

No problem por lo de docker.

**Comment by Spufy** [comment]
Nada sigue dando el mismo error.
LA versión de transmission remote : transmission-remote 2.94 (d8e60ee44f)
Otra cosa es que al acceder a la página de configuración me muestra 500 network error

**Comment by jerosoler** [comment]
Me recuerda a la issue:
https://github.com/jerosoler/newpct-total/issues/7

Echale un vistazo. 
Desde que url entras?

**Comment by Spufy** [comment]
He probado, lo anterior y nada.
Lo curioso es que funciona perfecto:
root@df327fa09ba5:/home/abc/newpct-total/server/api# npm start

> newpct-total@1.0.0 start /home/abc/newpct-total
> cross-env NODE_ENV=production node build/main.js

video-stream `factory.opts`: { dir: '/home/abc/newpct-total' }
Server listening on localhost3000
JSON Server is running
auth
URL final: http://tumejortorrent.com/?page=buscar&q=Buscar aqui..&calidad=
URL final: http://tumejortorrent.com/?page=buscar&q=Buscar aqui..&calidad=
auth
URL final: http://tumejortorrent.com/?page=buscar&q=Buscar aqui..&calidad=
URL final: http://tumejortorrent.com/?page=buscar&q=Buscar aqui..&calidad=
auth
URL final: http://tumejortorrent.com/?page=buscar&q=Buscar aqui..&calidad=
URL final: http://tumejortorrent.com/?page=buscar&q=Buscar aqui..&calidad=
URL final: http://tumejortorrent.com/?page=buscar&q=Buscar aqui..&calidad=HDTV 1080p AC3 5.1
URL final: http://tumejortorrent.com/?page=buscar&q=Buscar aqui..&pg=2&calidad=HDTV 1080p AC3 5.1
URL final: http://tumejortorrent.com/?page=buscar&q=Buscar aqui..&pg=3&calidad=HDTV 1080p AC3 5.1
Pero en cuanto seleccionas un torrente aparece el error

LLamado: http://tumejortorrent.com/descargar/peliculas-castellano/conexion-estambul/
hey
http:\/\/tumejortorrent.com\/.*?\"
null

/home/abc/newpct-total/build/webpack:/server/api/newpct.js:104
        urltorrent = urltorrent[0].slice(0,urltorrent[0].length-1);
                     ^
TypeError: Cannot read property '0' of null
    at Request._callback (/home/abc/newpct-total/build/webpack:/server/api/newpct.js:104:22)
    at Request.self.callback (/home/abc/newpct-total/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/home/abc/newpct-total/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/home/abc/newpct-total/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1107:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
ReferenceError: location is not defined
    at VueComponent.created (layouts/default.15f54c0918268c033d54.js:135:102)
    at callHook (/home/abc/newpct-total/node_modules/vue/dist/vue.runtime.common.js:3027:21)
    at VueComponent.Vue._init (/home/abc/newpct-total/node_modules/vue/dist/vue.runtime.common.js:4724:5)
    at new VueComponent (/home/abc/newpct-total/node_modules/vue/dist/vue.runtime.common.js:4890:12)
    at createComponentInstanceForVnode (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7316:10)
    at renderComponentInner (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7513:40)
    at renderComponent (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7488:5)
    at RenderContext.renderNode (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7404:5)
    at RenderContext.next (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:2469:23)
    at cachedWrite (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:2323:9)
    at renderElement (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7642:5)
    at renderNode (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7406:5)
    at renderComponentInner (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7524:3)
    at renderComponent (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7488:5)
    at RenderContext.renderNode (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7404:5)
    at RenderContext.next (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:2469:23)
ReferenceError: location is not defined
    at VueComponent.created (layouts/default.15f54c0918268c033d54.js:135:102)
    at callHook (/home/abc/newpct-total/node_modules/vue/dist/vue.runtime.common.js:3027:21)
    at VueComponent.Vue._init (/home/abc/newpct-total/node_modules/vue/dist/vue.runtime.common.js:4724:5)
    at new VueComponent (/home/abc/newpct-total/node_modules/vue/dist/vue.runtime.common.js:4890:12)
    at createComponentInstanceForVnode (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7316:10)
    at renderComponentInner (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7513:40)
    at renderComponent (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7488:5)
    at RenderContext.renderNode (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7404:5)
    at RenderContext.next (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:2469:23)
    at cachedWrite (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:2323:9)
    at renderElement (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7642:5)
    at renderNode (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7406:5)
    at renderComponentInner (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7524:3)
    at renderComponent (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7488:5)
    at RenderContext.renderNode (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7404:5)
    at RenderContext.next (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:2469:23)
ReferenceError: location is not defined
    at VueComponent.created (layouts/default.15f54c0918268c033d54.js:135:102)
    at callHook (/home/abc/newpct-total/node_modules/vue/dist/vue.runtime.common.js:3027:21)
    at VueComponent.Vue._init (/home/abc/newpct-total/node_modules/vue/dist/vue.runtime.common.js:4724:5)
    at new VueComponent (/home/abc/newpct-total/node_modules/vue/dist/vue.runtime.common.js:4890:12)
    at createComponentInstanceForVnode (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7316:10)
    at renderComponentInner (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7513:40)
    at renderComponent (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7488:5)
    at RenderContext.renderNode (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7404:5)
    at RenderContext.next (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:2469:23)
    at cachedWrite (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:2323:9)
    at renderElement (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7642:5)
    at renderNode (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7406:5)
    at renderComponentInner (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7524:3)
    at renderComponent (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7488:5)
    at RenderContext.renderNode (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:7404:5)
    at RenderContext.next (/home/abc/newpct-total/node_modules/vue-server-renderer/build.js:2469:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! newpct-total@1.0.0 start: `cross-env NODE_ENV=production node build/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the newpct-total@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-12T19_08_52_711Z-debug.log
root@df327fa09ba5:/home/abc/newpct-total/server/api# 

El acceso a la página es localhost:3000

**Comment by jerosoler** [comment]
Prueba con descargas2020.
Que puedeser que tumejortorrent no funcione

**Comment by jerosoler** [comment]
Desde el apartado config o si no eb el archivo db.json 

Al final asi
```  "urlsearch": {
    "url": "http://descargas2020.com/",
    "feed": "http://descargas2020.com/feed"
  }```

**Comment by Spufy** [comment]
Bueno, parece que ahora puede funcionar
me aparece un globo con el siguiente mensaje

Error
Error: Command failed: transmission-remote -a http://descargas2020.com/descargar-torrent/115865_-1544631798-impacto--bluray-1080p/ Unexpected response: <h1>401: Unauthorized</h1>Unauthorized User-www-form-urlencoded
 Unexpected response: <h1>401: Unauthorized</h1>Unauthorized User-www-form-urlencoded

pero esto creo que es un problema de usuario en el docker. Lo voy a mirar y ya te contaré.
Muchas gracias.

**Comment by Spufy** [comment]
Buenos días, comentarte que ya está funcionando perfectamente tu script con transmission en docker
Muchas gracias

**Comment by bepece1** [comment]
> Buenos días, comentarte que ya está funcionando perfectamente tu script con transmission en docker
> Muchas gracias

Me parece súper interesante. Por favor, ¿podrías compartir el código?

Gracias

**Comment by bepece1** [comment]
> > Buenos días, comentarte que ya está funcionando perfectamente tu script con transmission en docker
> > Muchas gracias
> 
> Me parece súper interesante. Por favor, ¿podrías compartir el código?
> 
> Gracias

@Spufy plisssss... sería genial que hicieras publico el código para "docketizar" newpct-total

Se tiene el visto bueno de @jerosoler (el autor de newpct-total)

Muchísimas gracias por tu aportación.

Un saludo.
